apiVersion: v2
name: istio-control
version: 1.20.0
description: Istio control plane (pilot + citadel)
type: application
dependencies:
  - name: pilot
    version: 1.20.0
  - name: citadel
    version: 1.20.0
