controller:
  replicaCount: 3
  image:
    repository: registry.k8s.io/ingress-nginx/controller
    tag: v1.10.0
  service:
    type: LoadBalancer
  config:
    use-proxy-protocol: true
    enable-brotli: true
