replicas: 2
image:
  repository: grafana/grafana
  tag: 10.4.0
adminUser: admin
adminPassword: admin
persistence:
  enabled: true
  size: 10Gi
plugins:
  - grafana-piechart-panel
  - grafana-clock-panel
