apiVersion: v2
name: kafka-cluster
version: 3.6.0
description: Kafka brokers + zookeeper + ecosystem
type: application
dependencies:
  - name: zookeeper
    version: 3.9.0
  - name: schema-registry
    version: 7.5.0
  - name: kafka-connect
    version: 7.5.0
